version: '3.4'
services:
  mallar-fe:
    container_name: mallar-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=http://localhost:8000/api
    expose:
      - 3000
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    tty: true
    command: ["npm", "start"]
    