version: '3'
services:
  mallar-fe:
    container_name: mallar-fe
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_HOST=http://cv-mallar.com/api
    ports:
      - 3000:3000
    expose:
      - 3000
    tty: true
    command: ["npm", "start"]
    